name: NameMCRewards
description: Reward your players for liking your server on NameMC.

website: savagedev.net
author: SavageAvocado

main: net.savagedev.namemcrewards.nukkit.NameMCRewardsNukkit
version: ${version}

commands:
  namemc:
    description: "Get a link to the server''s NameMC page."
    aliases: [ "nmc" ]
